apiVersion: v1
data:
  index.html: |-
    <html>
      <head>
        <title>Example App</title>
      </head>
      <body>
        <h1>Hello, World!</h1>
      </body>
    </html>

kind: ConfigMap
metadata:
  name: example-app-conf
  namespace: example-namespace
